config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :blogs do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, length: {in: 1..140}
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
              format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new(content: params[:content],user_id: @current_user.id)
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: "Yeah！！ブログを作成したYO！！"
    else
      render :new
    end
  end

  def show
    @blog = Blog.find_by(id: params[:id])
    @user = User.find_by(id: @blog.user_id)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "Hey！！ブログを編集したYO！！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"Uh-oh.ブログを削除したYO！！"
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.id = params[:id]
    @blog.user_id = current_user.id
    if @blog.user_id?
      render :edit and return if @blog.invalid?
    else
      render :new if @blog.invalid?
    end

  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache, :remove_image)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
      flash[:notice] = 'Welcome!! ログアインしました！！'
    else
      flash.now[:danger] = 'Ouch！! ログインに失敗しました！！'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'see ya!! ログアウトしました！！'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def url_confirm
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit' || action_name == 'update'
      confirm_blog_path
    end
  end

  def edit_confirm
    unless @blog.id
      blogs_path
    else
      blog_path
    end
  end

  def method_confirm
    @blog.id ? 'patch' : 'post'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: url_confirm, method: method_confirm) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>Ooops!!<%= @blog.errors.count %>件のエラーがありまっせ～！！</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="field">
    <% if @blog.image? %>
      <div class="thumbnail">
      <%= image_tag @blog.image.url %>
    </div>
  <% end %><br>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="field">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if @blog.persisted? && @blog.image? %>
      <label>
      <%= form.check_box :remove_image %>
      画像を削除
    </label>
  <% end %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "ブログ一覧画面にもどる", blogs_path, class: "btn btn-outline-primary"  %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, url: edit_confirm, method: method_confirm, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :user_id, value: current_user.id %>
    <p>タイトル:<%= @blog.title %></p>
    <p>本文:<%= @blog.content %></p>
    <p>画像:<%= image_tag @blog.image.url if @blog.image? %></p>
  <%= form.submit  "登録する",  class: "btn btn-outline-primary" %>
<%= form.submit "戻る", name: 'back', class: "btn btn-outline-primary"  %>
<% end %>

app/views/blogs/edit.html.erb
  <h2>ブログを編集する</h2>
  <%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= image_tag blog.image.url if blog.image? %></td>
    <td><%= blog.user.name %></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id), class: "btn btn-outline-primary" %></td>
    <td><%= link_to "ブログを編集する", edit_blog_path(blog.id), class: "btn btn-outline-primary"  %></td>
    <td><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: 'マジで！？削除していいの？？本当に？？' }, class: "btn btn-outline-primary"  %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくブログを投稿する', new_blog_path, class: "btn btn-outline-primary"  %>

app/views/blogs/new.html.erb
  <h2>ブログを作成する</h2>
  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>ユーザー名: <%= @blog.user.name %></p>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image.url %>
</p>

<p>
<strong>Image:</strong>
<% if @blog.image? %>
  <div class="thumbnail">
  <%= image_tag @blog.image.url %>
</div>
<% end %>
</p>

<%= link_to '編集する', edit_blog_path(@blog), class: "btn btn-outline-primary"  %> |
<%= link_to '戻る', blogs_path, class: "btn btn-outline-primary"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>複製顔本</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>

  <body>
    <header class = "header">
    <h1>複製顔本</h1>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Blog", blogs_path %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
    <footer class = "footer">
    <h6>© 2021 DIC WEF_2103 謹製</h6>
    </footer>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>

</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>